name: On release build

permissions:
  contents: read
  packages: write


on:
  workflow_dispatch:
  release:
    types: [published]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date -u +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push
        uses: rdinit/itam_cicd@v1
        with:
          registry-url: ${{ secrets.REGISTRY_URL }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.GITHUB_TOKEN }} 
          image-name: ${{ secrets.SERVICE_NAME }}:itam_hack_service${{ steps.timestamp.outputs.timestamp }}
