name: On release build

permissions:
  contents: read
  packages: write


on:
  release:
    types: [published]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push
        uses: rdinit/itam_cicd@v1
        with:
          registry-url: ${{ secrets.REGISTRY_URL }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.GITHUB_TOKEN }} 
          image-name: ${{ secrets.SERVICE_NAME }}:${{ github.event.inputs.tag }}
